networks:
  proxy:
    external: true

services:
  Info:
    container_name: info
    image: onboarding-info:latest
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.89.1.251
    volumes:
      - "~/infoProd.env:/server/.env"