networks:
  proxy:
    external: true

services:
  previewInfo:
    container_name: infopreview
    image: onboarding-info-preview:latest
    restart: unless-stopped
    networks:
      proxy:
        ipv4_address: 10.89.1.151
    volumes:
      - "~/infoPreview.env:/server/.env"