import fs from "fs";
import {getRole, verifyToken} from "~~~/server/jwt";
import {updateConfigValue,getConfigValue} from "~~/server/database"
import event from "./event";


/**
 * 
 * @openapi
 * /discord:
 *     get:
 *     tags:
 *      - Discord QR Code displaying
 *     security:
 *      - JWT: []
 *     description: "Displays a QR Code generated by a link to get invited to the discord servor"
 *     responses:
 *       200:
 *         description: "Return the default discord servor's link"
 *              content : 
 *                  application/json:
 *                      schema:
 *                          type : object
 *                          properties:
 *                              link:
 *                                  type: string
 *                                  example: "/DefaultDiscord"
 *     put:
 *      tags:
 *          - Culture meetings management
 *      security:
 *          - JWT: []
 *      description: "Modify an existing event"
 *      request-body:
 *          required:true
 *      parameters:
 *          -in:query
 *          name:"link"
 *          required:true
 *          schema:
 *              type:string
 *          description:"Discord link choosen"
 *      responses:
 *          200:
 *              description: "Discord link choosen"
 *          401:
 *              description: "User is not logged in"
 *          403: 
 *              description: "User doesn't have access to this page"
 */


async function handler(req) {
    let body;
    let token = parseCookies(req)?.onboardingToken
    let data

    try {
        switch(req.method) {
            case "PUT":
                if(await verifyToken(token) === false) {
                    return new Response(JSON.stringify({message:"Invalid token"}), {status: 401});
                }

                let roles = await getRole(token);

                if(roles === -1 || !(roles.includes("ADMIN") || roles.includes("BDE") || roles.includes("MAINTAINER"))) {
                    return new Response(JSON.stringify({message:"Permission denied."}), {status: 403});
                }
                body = await readBody(req);
                let tmp = await body.json();
                data.BDEDiscordLink = tmp.link;
                fs.writeFileSync("../../../data.json", JSON.stringify(data));
                return new Response(JSON.stringify({message:null}), {status: 200});
            case "GET":
                let {BDEDiscordLink} = data;
                return new Response(BDEDiscordLink, {status: 200});
            default:
                return new Response(JSON.stringify({message:"Method not allowed. Please read the documentation."}), {status: 405});
        }
    } catch (error) {
        return new Response(JSON.stringify({message:`Internal Server Error: ${error.message}`}), {status: 500});
    }
}

export default eventHandler(handler);
