import {getRole, verifyToken} from "~~/server/jwt";
import {updateConfigValue,getConfigValue} from "~~/server/database"

/**
 * @openapi
 * /discord:
 *     get:
 *         tags:
 *             - Discord QR Code displaying
 *         summary: "Displays a QR Code generated by a link to get invited to the discord server"
 *         responses:
 *             200:
 *                 description: "Return the default discord server's link"
 *                 content:
 *                     text/plain:
 *                         type: string
 *                         example: "https://google.com/"
 *
 *     put:
 *         tags:
 *             - Discord QR Code displaying
 *         security:
 *             - JWT: []
 *         summary: "Update the Discord invitation link"
 *         requestBody:
 *             required: true
 *             content:
 *                 application/json:
 *                     schema:
 *                         type: object
 *                         properties:
 *                             link:
 *                                 type: string
 *                                 description: "Discord link chosen"
 *                                 example: "/MyDiscordInvite"
 *                         required:
 *                             - link
 *         responses:
 *             200:
 *                 description: "Discord link updated"
 *             400:
 *                 description: "Invalid link format"
 *             401:
 *                 description: "User is not logged in"
 *             403: 
 *                 description: "User doesn't have access to this page"
 *             500:
 *                 description: "Unknown error"
 */
async function handler(req: any) {
    let body;
    let token = parseCookies(req)?.onboardingToken

    try {
        switch(req.method) {
            case "PUT":
                if(await verifyToken(token) === false) {
                    return new Response(JSON.stringify({message:"Invalid token"}), {status: 401});
                }

                let roles = await getRole(token);

                if(roles === -1 || !(roles.includes("ADMIN") || roles.includes("BDE") || roles.includes("MAINTAINER"))) {
                    return new Response(JSON.stringify({message:"Permission denied."}), {status: 403});
                }
                body = await readBody(req);
                let tmp = JSON.parse(body)
                let data = {key: "BDEdiscord", value: tmp.link}
                await updateConfigValue(data);
                return new Response(JSON.stringify({message:null}), {status: 200});
            case "GET":
                let BDEDiscordLink = await getConfigValue("BDEdiscord");
                if (!BDEDiscordLink) throw Error("No value found");
                return new Response(BDEDiscordLink.value, {status: 200});
            default:
                return new Response(JSON.stringify({message:"Method not allowed. Please read the documentation."}), {status: 405});
        }
    } catch (error: any) {
        return new Response(JSON.stringify({message:`Internal Server Error: ${error.message}`}), {status: 500});
    }
}

export default eventHandler(handler);

